import json

notebook_path = "notebooks/00_end_to_end_pipeline.ipynb"

with open(notebook_path, "r", encoding="utf-8") as f:
    nb = json.load(f)

# Find step 2 code cell
cell_idx = None
for idx, cell in enumerate(nb["cells"]):
    if cell["cell_type"] == "code" and any("USE_REAL_DATASET" in line for line in cell["source"]):
        cell_idx = idx
        break

if cell_idx is not None:
    print(f"Found dataset setup cell at index {cell_idx}")
    
    # We will construct the new source for this cell
    new_source = [
        "USE_REAL_DATASET = True  # Toggle this to False to run on a fast simulated mock dataset instead\n",
        "\n",
        "raw_dir = Path(\"../data/raw\")\n",
        "raw_dir.mkdir(parents=True, exist_ok=True)\n",
        "np.random.seed(42)\n",
        "\n",
        "if USE_REAL_DATASET:\n",
        "    print(\"=== Setting up Real Biological Datasets ===\")\n",
        "    import urllib.request\n",
        "    import gzip\n",
        "    import shutil\n",
        "    \n",
        "    # 1. Download TWOSIDES\n",
        "    twosides_dest = raw_dir / \"TWOSIDES.csv\"\n",
        "    if not twosides_dest.exists():\n",
        "        twosides_url = \"https://tatonettilab-resources.s3.us-west-1.amazonaws.com/nsides/TWOSIDES.csv.gz\"\n",
        "        print(f\"Downloading real TWOSIDES from {twosides_url}...\")\n",
        "        try:\n",
        "            twosides_gz = raw_dir / \"TWOSIDES.csv.gz\"\n",
        "            urllib.request.urlretrieve(twosides_url, twosides_gz)\n",
        "            print(\"Extracting TWOSIDES...\")\n",
        "            with gzip.open(twosides_gz, 'rb') as f_in:\n",
        "                with open(twosides_dest, 'wb') as f_out:\n",
        "                    shutil.copyfileobj(f_in, f_out)\n",
        "            print(\"TWOSIDES download and extraction complete.\")\n",
        "        except Exception as e:\n",
        "            print(f\"Failed to download TWOSIDES: {e}. Fallback to simulated data.\")\n",
        "            twosides_rows = []\n",
        "            for _ in range(300):\n",
        "                d1 = f\"DB{np.random.randint(0, 100):05d}\"\n",
        "                d2 = f\"DB{np.random.randint(0, 100):05d}\"\n",
        "                if d1 != d2:\n",
        "                    se = f\"SE{np.random.randint(0, 10):03d}\"\n",
        "                    twosides_rows.append({'drug1': d1, 'drug2': d2, 'side_effect': se})\n",
        "            pd.DataFrame(twosides_rows).drop_duplicates().to_csv(twosides_dest, index=False)\n",
        "            print(\"Fallback simulated TWOSIDES generated.\")\n",
        "    else:\n",
        "        print(\"Real TWOSIDES dataset found.\")\n",
        "        \n",
        "    # 2. Download SIDER\n",
        "    sider_dest = raw_dir / \"sider.tsv\"\n",
        "    if not sider_dest.exists():\n",
        "        sider_url = \"http://sideeffects.embl.de/media/download/meddra_all_se.tsv.gz\"\n",
        "        print(f\"Downloading real SIDER from {sider_url}...\")\n",
        "        try:\n",
        "            sider_gz = raw_dir / \"sider.tsv.gz\"\n",
        "            urllib.request.urlretrieve(sider_url, sider_gz)\n",
        "            with gzip.open(sider_gz, 'rb') as f_in:\n",
        "                with open(sider_dest, 'wb') as f_out:\n",
        "                    shutil.copyfileobj(f_in, f_out)\n",
        "            print(\"SIDER download and extraction complete.\")\n",
        "        except Exception as e:\n",
        "            print(f\"Failed to download SIDER: {e}.\")\n",
        "    else:\n",
        "        print(\"Real SIDER dataset found.\")\n",
        "        \n",
        "    # 3. Download STRING protein-protein links\n",
        "    string_dest = raw_dir / \"9606.protein.links.v12.0.txt\"\n",
        "    if not string_dest.exists():\n",
        "        string_url = \"https://stringdb-downloads.org/download/protein.links.v12.0/9606.protein.links.v12.0.txt.gz\"\n",
        "        print(f\"Downloading real STRING from {string_url}...\")\n",
        "        try:\n",
        "            string_gz = raw_dir / \"9606.protein.links.v12.0.txt.gz\"\n",
        "            urllib.request.urlretrieve(string_url, string_gz)\n",
        "            with gzip.open(string_gz, 'rb') as f_in:\n",
        "                with open(string_dest, 'wb') as f_out:\n",
        "                    shutil.copyfileobj(f_in, f_out)\n",
        "            print(\"STRING download and extraction complete.\")\n",
        "        except Exception as e:\n",
        "            print(f\"Failed to download STRING: {e}.\")\n",
        "    else:\n",
        "        print(\"Real STRING dataset found.\")\n",
        "        \n",
        "    # 4. Check for DrugBank XML file (downloading from working repository URL)\n",
        "    drugbank_xml = raw_dir / \"drugbank.xml\"\n",
        "    if not drugbank_xml.exists():\n",
        "        drugbank_url = \"https://huggingface.co/datasets/agenticx/DrugBank/resolve/main/drugbank_full_database.xml\"\n",
        "        print(f\"Downloading real DrugBank XML from {drugbank_url}...\")\n",
        "        try:\n",
        "            urllib.request.urlretrieve(drugbank_url, drugbank_xml)\n",
        "            print(\"DrugBank XML download complete.\")\n",
        "        except Exception as e:\n",
        "            print(f\"Failed to download DrugBank XML: {e}. Fallback to simulated drugbank.xml\")\n",
        "            root_el = ET.Element(\"drugs\", attrib={'xmlns': 'http://www.drugbank.ca'})\n",
        "            for i in range(100):\n",
        "                drug = ET.SubElement(root_el, \"{http://www.drugbank.ca}drug\")\n",
        "                db_id = ET.SubElement(drug, \"{http://www.drugbank.ca}drugbank-id\", attrib={'primary': 'true'})\n",
        "                db_id.text = f\"DB{i:05d}\"\n",
        "                targets = ET.SubElement(drug, \"{http://www.drugbank.ca}targets\")\n",
        "                for _ in range(np.random.randint(1, 5)):\n",
        "                    target = ET.SubElement(targets, \"{http://www.drugbank.ca}target\")\n",
        "                    uniprot = ET.SubElement(target, \"{http://www.drugbank.ca}uniprot-id\")\n",
        "                    uniprot.text = f\"P{np.random.randint(0, 200):05d}\"\n",
        "            tree = ET.ElementTree(root_el)\n",
        "            tree.write(drugbank_xml, encoding='utf-8', xml_declaration=True)\n",
        "            print(\"Fallback simulated drugbank.xml generated.\")\n",
        "    else:\n",
        "        print(\"Real DrugBank XML dataset found.\")\n",
        "else:\n",
        "    print(\"=== Generating Fully Simulated Mock Dataset ===\")\n",
        "    num_mock_drugs = 50\n",
        "    num_mock_proteins = 100\n",
        "    num_mock_side_effects = 10\n",
        "    \n",
        "    # Generate mock DrugBank\n",
        "    xml_path = raw_dir / \"drugbank.xml\"\n",
        "    root_el = ET.Element(\"drugs\", attrib={'xmlns': 'http://www.drugbank.ca'})\n",
        "    for i in range(num_mock_drugs):\n",
        "        drug = ET.SubElement(root_el, \"{http://www.drugbank.ca}drug\")\n",
        "        db_id = ET.SubElement(drug, \"{http://www.drugbank.ca}drugbank-id\", attrib={'primary': 'true'})\n",
        "        db_id.text = f\"DB{i:05d}\"\n",
        "        targets = ET.SubElement(drug, \"{http://www.drugbank.ca}targets\")\n",
        "        for _ in range(np.random.randint(1, 6)):\n",
        "            target = ET.SubElement(targets, \"{http://www.drugbank.ca}target\")\n",
        "            uniprot = ET.SubElement(target, \"{http://www.drugbank.ca}uniprot-id\")\n",
        "            uniprot.text = f\"P{np.random.randint(0, num_mock_proteins):05d}\"\n",
        "    tree = ET.ElementTree(root_el)\n",
        "    tree.write(xml_path, encoding='utf-8', xml_declaration=True)\n",
        "    \n",
        "    # Generate mock TWOSIDES\n",
        "    twosides_rows = []\n",
        "    for _ in range(300):\n",
        "        d1 = f\"DB{np.random.randint(0, num_mock_drugs):05d}\"\n",
        "        d2 = f\"DB{np.random.randint(0, num_mock_drugs):05d}\"\n",
        "        if d1 != d2:\n",
        "            se = f\"SE{np.random.randint(0, num_mock_side_effects):03d}\"\n",
        "            twosides_rows.append({'drug1': d1, 'drug2': d2, 'side_effect': se})\n",
        "    pd.DataFrame(twosides_rows).drop_duplicates().to_csv(raw_dir / \"TWOSIDES.csv\", index=False)\n",
        "    \n",
        "    # Generate mock STRING\n",
        "    string_rows = []\n",
        "    for _ in range(500):\n",
        "        p1 = f\"9606.ENSP{np.random.randint(0, num_mock_proteins):05d}\"\n",
        "        p2 = f\"9606.ENSP{np.random.randint(0, num_mock_proteins):05d}\"\n",
        "        if p1 != p2:\n",
        "            string_rows.append({'protein1': p1, 'protein2': p2, 'combined_score': np.random.choice([200, 500, 800, 950])})\n",
        "    pd.DataFrame(string_rows).drop_duplicates().to_csv(raw_dir / \"9606.protein.links.v12.0.txt\", sep=\" \", index=False)\n",
        "    print(\"Simulated mock datasets generated successfully.\")"
    ]
    
    nb["cells"][cell_idx]["source"] = new_source
    
    with open(notebook_path, "w", encoding="utf-8") as f:
        json.dump(nb, f, indent=1)
    print("Notebook updated successfully!")
else:
    print("Failed to find dataset setup cell in the notebook.")
