import re
from pathlib import Path

def main():
    responses_path = Path("paper/reviewer_responses.md")
    content = responses_path.read_text()

    # Define all replacements
    replacements = [
        # Replacement 1
        (
            "* **Response**: We thank the reviewer for raising this key point. We agree that Attention Rollout (necessity 0.0044) and GNNExplainer (necessity 0.0000) fail to identify causal subgraphs. In complex multi-relational graphs, heuristic rollout and unconstrained mutual information optimization tend to highlight highly active hub nodes (e.g. widely interacting proteins) rather than specific paths. When these hub nodes are deleted, the GNN simply routes message propagation through alternative, redundant links, resulting in a near-zero change in predictions. These methods thus provide descriptive (correlated) rather than counterfactual explanations.\n \n  In contrast, KEC achieves a substantially higher necessity (Fidelity+) score of **0.0371**, demonstrating that its explanations behave as highly influential edges under a counterfactual perturbation framework. We have updated **Section 5.6 (Discussion)** to emphasize this distinction between descriptive and perturbation-based counterfactual explainers, and have explained PGExplainer's slightly negative necessity (-0.0045) as a structural artifact of mask perturbation in dense regions.",
            "* **Response**: We thank the reviewer for raising this key point. We agree that Attention Rollout (necessity -0.0008) and GNNExplainer (necessity -0.0000) fail to identify causal subgraphs. In complex multi-relational graphs, heuristic rollout and unconstrained mutual information optimization tend to highlight highly active hub nodes (e.g. widely interacting proteins) rather than specific paths. When these hub nodes are deleted, the GNN simply routes message propagation through alternative, redundant links, resulting in a near-zero change in predictions. These methods thus provide descriptive (correlated) rather than counterfactual explanations.\n \n  In contrast, PGExplainer achieves a necessity (Fidelity+) score of **0.0443** and KEC achieves **0.0282**, demonstrating that their explanations successfully act as functional bottlenecks under a counterfactual perturbation framework. We have updated **Section 5.6 (Discussion)** to emphasize this distinction between descriptive and perturbation-based counterfactual explainers, and have explained Attention Rollout's slightly negative necessity (-0.0008) as a structural artifact of mask perturbation in dense regions."
        ),
        # Replacement 2
        (
            "* **Response**: We thank the reviewer for this observation. We agree that claiming KEC superiority over all baseline explainers across all metrics is not justified. In the updated results, PGExplainer achieves the highest overall sufficiency (0.7480) and GNNExplainer achieves the highest local sparsity (1.0000), while KEC is best understood as a complementary method that achieves the highest necessity (Fidelity+ of 0.0371) and highest lenient path connectivity (40.0%).\n \n  Regarding statistical significance, we have performed Wilcoxon signed-rank testing with Holm–Bonferroni correction (summarized in Section 5.6.3), which confirms that only the Fidelity+ necessity improvement of KEC over GNNExplainer remains statistically significant after correction (adjusted $p = 0.0396$), while KEC's necessity improvements over Attention and PGExplainer do not survive correction.\n\n  We have refocused the discussion in **Section 5.6** on the trade-off between explanation faithfulness, complexity, and topological structure. KEC achieves high necessity (Fidelity+ of 0.0371) while maintaining high local sparsity of **0.9949** (retaining only ~4 edges). Across all methods, strict path connectivity of the final subgraphs is low (9.0% for Attention, 5.0% for PGExplainer, 2.0% for KEC) due to the localized learning bottleneck of the GNN. However, KEC achieves a lenient connectivity of **40.0%** (with an average hop distance of **3.60**), confirming that KEC's counterfactual edge cuts are positioned along valid multi-hop drug-target pathways in the original clinical graph.",
            "* **Response**: We thank the reviewer for this observation. We agree that claiming KEC superiority over all baseline explainers across all metrics is not justified. In the updated results, GNNExplainer achieves the highest overall sufficiency (0.7922) and the highest local sparsity (1.0000), while PGExplainer achieves the highest necessity (Fidelity+ of 0.0443) and KEC achieves the highest lenient path connectivity (46.5%).\n \n  Regarding statistical significance, we have performed Wilcoxon signed-rank testing with Holm–Bonferroni correction (summarized in Section 5.6.3), which confirms that the Fidelity+ necessity difference is statistically significant for PGExplainer vs. Attention (adjusted $p = 0.0077$) and PGExplainer vs. GNNExplainer (adjusted $p = 0.0050$), while comparisons involving KEC do not survive the multiple-comparison correction (adjusted $p = 0.0523$).\n\n  We have refocused the discussion in **Section 5.6** on the trade-off between explanation faithfulness, complexity, and topological structure. PGExplainer achieves a Fidelity+ of 0.0443 with a local sparsity of 0.9990, while KEC achieves a Fidelity+ of 0.0282 with a local sparsity of **0.9984** (retaining only ~1-2 edges). Across all methods, strict path connectivity of the final subgraphs is low (3.0% for Attention, 2.0% for PGExplainer, 2.0% for KEC) due to the localized learning bottleneck of the GNN. However, KEC achieves a lenient connectivity of **46.5%** (with an average hop distance of **3.80**), confirming that KEC's counterfactual edge cuts are positioned along valid multi-hop drug-target pathways in the original clinical graph."
        ),
        # Replacement 3
        (
            "* **Response**: We thank the reviewer for this suggestion. We have updated Table 5.5.1 to ensure the bolding correctly highlights the mathematically ideal performance in each column under the dense graph configuration. Specifically:\n  - For Sufficiency, PGExplainer's value of `0.7480` (highest) is bolded.\n  - For Fidelity+ (Comprehensiveness), KEC's value of `0.0371` (highest probability drop) is bolded.\n  - For Fidelity- (Sufficiency probability change), Attention Rollout's value of `0.0897` (lowest probability difference) is bolded.\n  - For Sparsity (Local), GNNExplainer's value of `1.0000` (highest fraction of edges omitted) is bolded.\n  - For Strict Connectivity, Attention Rollout's value of `9.0%` (highest) is bolded.\n  - For Lenient Connectivity, KEC's value of `40.0%` (highest) is bolded.\n  - We expanded the footnote to explain the standard deviations and report that only KEC vs. GNNExplainer remains statistically significant after Holm–Bonferroni correction ($p < 0.05$), with KEC's necessity improvement over Attention and PGExplainer being raw-significant at $p < 0.05$ but not surviving Holm–Bonferroni correction.",
            "* **Response**: We thank the reviewer for this suggestion. We have updated Table 5.5.1 to ensure the bolding correctly highlights the mathematically ideal performance in each column under the dense graph configuration. Specifically:\n  - For Sufficiency, GNNExplainer's value of `0.7922` (highest) is bolded.\n  - For Fidelity+ (Comprehensiveness), PGExplainer's value of `0.0443` (highest probability drop) is bolded.\n  - For Fidelity- (Sufficiency probability change), Attention Rollout's value of `0.0889` (lowest probability difference) is bolded.\n  - For Sparsity (Local), GNNExplainer's value of `1.0000` (highest fraction of edges omitted) is bolded.\n  - For Strict Connectivity, Attention Rollout's value of `3.0%` (highest) is bolded.\n  - For Lenient Connectivity, KEC's value of `46.5%` (highest) is bolded.\n  - We expanded the footnote to explain the standard deviations and report that the Fidelity+ differences are statistically significant for PGExplainer vs. Attention (adjusted $p = 0.0077$) and PGExplainer vs. GNNExplainer (adjusted $p = 0.0050$), while comparisons involving KEC do not survive the multiple-comparison correction threshold (adjusted $p = 0.0523$)."
        ),
        # Replacement 4
        (
            "  - In Section 5.6 point 1, we explain that PGExplainer's negative Fidelity+ (`-0.0045`) indicates removing its edges increases prediction probability, which is a structural artifact of mask perturbation in dense regions (removing critical edges can remove competing features/noise or trigger out-of-distribution model behavior).",
            "  - In Section 5.6 point 1, we explain that Attention Rollout's negative Fidelity+ (`-0.0008`) indicates removing its edges slightly increases prediction probability, which is a structural artifact of mask perturbation in dense regions (removing critical edges can remove competing features/noise or trigger out-of-distribution model behavior)."
        ),
        # Replacement 5
        (
            "* **Response**: We have removed the placeholders and fully populated the table in **Section 5.6.3 (Statistical Significance & Effect Sizes)** with the actual computed results of the two-sided Wilcoxon signed-rank tests and Holm–Bonferroni corrections. The statistical significance values match the results reported in Table 5.5.1, demonstrating that only the comparison of KEC vs. GNNExplainer remains statistically significant after Holm–Bonferroni correction (adjusted $p = 0.0396$), while KEC's necessity improvements over Attention ($p = 0.0169$ raw) and PGExplainer ($p = 0.0322$ raw) are raw-significant at $p < 0.05$ but do not survive the multiple testing correction.",
            "* **Response**: We have removed the placeholders and fully populated the table in **Section 5.6.3 (Statistical Significance & Effect Sizes)** with the actual computed results of the two-sided Wilcoxon signed-rank tests and Holm–Bonferroni corrections. The statistical significance values match the results reported in Table 5.5.1, demonstrating that the comparisons of PGExplainer vs. Attention (adjusted $p = 0.0077$) and PGExplainer vs. GNNExplainer (adjusted $p = 0.0050$) are statistically significant after Holm–Bonferroni correction, while KEC's necessity improvements over Attention and GNNExplainer (adjusted $p = 0.0523$) do not survive the multiple testing correction."
        ),
        # Replacement 6
        (
            "  - In our updated dense graph experiments, KEC's Fidelity+ is **positive** (`0.0371`), and Attention is also **positive** (`0.0044`), indicating that deleting their subgraphs successfully drops prediction confidence, confirming they act as necessary causal bottlenecks.\n  - We clearly state that only PGExplainer exhibits a slightly negative Fidelity+ value (`-0.0045`), and we discuss this as a structural artifact of amortized global optimization under dense relational graphs rather than a general failure of explanation necessity.",
            "  - In our updated dense graph experiments, PGExplainer's Fidelity+ is **positive** (`0.0443`), and KEC is also **positive** (`0.0282`), indicating that deleting their subgraphs successfully drops prediction confidence, confirming they act as necessary causal bottlenecks.\n  - We clearly state that only Attention Rollout exhibits a slightly negative Fidelity+ value (`-0.0008`), and we discuss this as a structural artifact of mask perturbation in dense relational graphs rather than a general failure of explanation necessity."
        ),
        # Replacement 7
        (
            "  * **Response**: We have rerun all GNN ablation configurations (FULL, NO_PPI, NO_GNN) on the dense graph to full 100-epoch convergence and reported them in Table 5.5.2. Interestingly, even on the dense graph, the FULL model (0.8536 AUROC) performs slightly worse than the NO_PPI ablation (0.8544 AUROC) by 0.0008.",
            "  * **Response**: We have rerun all GNN ablation configurations (FULL, NO_PPI, NO_GNN) on the dense graph to full 100-epoch convergence and reported them in Table 5.5.2. Interestingly, even on the dense graph, the FULL model (0.8538 AUROC) performs slightly worse than the NO_PPI ablation (0.8543 AUROC) by 0.0005."
        ),
        # Replacement 8
        (
            "* **Response**: We thank the reviewer for identifying this statistical error. The reviewer is correct: the p-values reported are raw, and only the comparison of KEC vs. GNNExplainer ($p = 0.0066$) survives the Holm–Bonferroni correction (adjusted $p = 0.0396 \\le 0.05$ for $m=6$ tests). The improvements of KEC over Attention ($p = 0.0169$ raw, adjusted $p = 0.0845$) and PGExplainer ($p = 0.0322$ raw, adjusted $p = 0.1288$) are raw-significant at $p < 0.05$ but do not survive Holm–Bonferroni correction. We have corrected these claims in the footnote of Table 5.5.1, the discussion text in Section 5.6 point 1, and the pairwise statistical significance table in Section 5.6.3 to represent these statistical boundaries transparently. We also added the missing pairwise comparison between Attention and GNNExplainer ($p=0.9659$, effect size=0.1810, Significant: No) in Section 5.6.3.",
            "* **Response**: We thank the reviewer for identifying this statistical error. The reviewer is correct: the p-values reported are raw, and only the comparisons of PGExplainer vs. Attention (adjusted $p = 0.0077$) and PGExplainer vs. GNNExplainer (adjusted $p = 0.0050$) survive the Holm–Bonferroni correction. The improvements of KEC over Attention (adjusted $p = 0.0523$) and GNNExplainer (adjusted $p = 0.0523$) do not survive the multiple testing correction. We have corrected these claims in the footnote of Table 5.5.1, the discussion text in Section 5.6 point 1, and the pairwise statistical significance table in Section 5.6.3 to represent these statistical boundaries transparently. We also added the missing pairwise comparison between Attention and GNNExplainer ($p=0.3362$, effect size=-0.3339, Significant: No) in Section 5.6.3."
        ),
        # Replacement 9
        (
            "* **Response**: We have implemented a random edge-selection baseline (selecting $k=4$ random edges from the candidate neighborhoods) over 100 trials across all 100 sample pairs. The baseline yields exactly **0.00%** lenient connectivity when selecting from all local subgraph edges and **0.03%** lenient connectivity when restricted to KEC candidate edges. This demonstrates that KEC's lenient connectivity score of **40.0%** (with an average hop distance of **3.60**, where a shorter hop distance represents a more direct pathway) is highly non-trivial and represents a significant structural pathway alignment above chance. We have integrated this baseline comparison into Table 5.5.1, the footnote, and the connectivity discussion in Section 5.6 point 3.",
            "* **Response**: We have implemented a random edge-selection baseline (selecting $k=4$ random edges from the candidate neighborhoods) over 100 trials across all 100 sample pairs. The baseline yields exactly **0.00%** lenient connectivity when selecting from all local subgraph edges and **0.03%** lenient connectivity when restricted to KEC candidate edges. This demonstrates that KEC's lenient connectivity score of **46.5%** (with an average hop distance of **3.80**, where a shorter hop distance represents a more direct pathway) is highly non-trivial and represents a significant structural pathway alignment above chance. We have integrated this baseline comparison into Table 5.5.1, the footnote, and the connectivity discussion in Section 5.6 point 3."
        ),
        # Replacement 10
        (
            "* **Response**: We agree that this is a critical limitation of transductive DDI prediction models. We have reframed Section 5.1 and Section 5.3.3 to re-scope Chapter 5 as a methodology-oriented study of GNN explainability and faithfulness (exploring model-representation reflection rather than benchmarking predictive models). In Section 5.6 point 1, we add a dedicated discussion of near-zero Fidelity+ values, characterizing them as a systemic limit of perturbation-based faithfulness metrics on redundant transductive graphs, and explain how KEC's positive Fidelity+ ($0.0371$) acts as a functional bottleneck compared to PGExplainer's negative values ($-0.0045$).",
            "* **Response**: We agree that this is a critical limitation of transductive DDI prediction models. We have reframed Section 5.1 and Section 5.3.3 to re-scope Chapter 5 as a methodology-oriented study of GNN explainability and faithfulness (exploring model-representation reflection rather than benchmarking predictive models). In Section 5.6 point 1, we add a dedicated discussion of near-zero Fidelity+ values, characterizing them as a systemic limit of perturbation-based faithfulness metrics on redundant transductive graphs, and explain how PGExplainer's positive Fidelity+ ($0.0443$) and KEC's positive Fidelity+ ($0.0282$) act as functional bottlenecks compared to Attention Rollout's negative values ($-0.0008$)."
        ),
        # Replacement 11
        (
            "  These findings explain why the FULL model (0.8536 AUROC) performs slightly worse than the NO_PPI model (0.8544 AUROC) by 0.0008, confirming that simply resolving network sparsity is insufficient without architectural oversmoothing mitigation.",
            "  These findings explain why the FULL model (0.8538 AUROC) performs slightly worse than the NO_PPI model (0.8543 AUROC) by 0.0005, confirming that simply resolving network sparsity is insufficient without architectural oversmoothing mitigation."
        ),
        # Replacement 12
        (
            "* **Concern**: *A Fidelity+ value of 0.0371 is statistically larger than the alternatives but represents a small average probability change (3.7%). Wording should be qualified to avoid over-claiming.*\n* **Response**: We have updated Section 5.6 point 1 to tone down necessity claims. Instead of framing KEC's subgraphs as \"highly essential\", we now describe them as \"relatively more influential than the alternatives evaluated\" and \"successfully acting as functional bottlenecks under a counterfactual perturbation framework.\"",
            "* **Concern**: *A Fidelity+ value of 0.0282 for KEC and 0.0443 for PGExplainer are statistically larger than the alternatives but represent small average probability changes. Wording should be qualified to avoid over-claiming.*\n* **Response**: We have updated Section 5.6 point 1 to tone down necessity claims. Instead of framing these subgraphs as \"highly essential\", we now describe them as \"relatively more influential than the alternatives evaluated\" and \"successfully acting as functional bottlenecks under a counterfactual perturbation framework.\""
        ),
        # Replacement 13
        (
            "* **Concern**: *Reporting mean values without standard deviations or confidence intervals makes it impossible to judge the significance of small differences (e.g. PGExplainer 0.7480 sufficiency vs. Attention 0.7422).*\n* **Response**: We have fully updated Table 5.5.1 to report all faithfulness metrics (Sufficiency, Fidelity+, Fidelity-, and Sparsity) as **Mean ± SD** calculated across the 100 randomly sampled drug pairs. For example, PGExplainer Sufficiency is reported as $0.7480 \\pm 0.3287$ and Attention Sufficiency as $0.7422 \\pm 0.3133$.",
            "* **Concern**: *Reporting mean values without standard deviations or confidence intervals makes it impossible to judge the significance of small differences (e.g. PGExplainer 0.7850 sufficiency vs. Attention 0.7916).*\n* **Response**: We have fully updated Table 5.5.1 to report all faithfulness metrics (Sufficiency, Fidelity+, Fidelity-, and Sparsity) as **Mean ± SD** calculated across the 100 randomly sampled drug pairs. For example, PGExplainer Sufficiency is reported as $0.7850 \\pm 0.2959$ and Attention Sufficiency as $0.7916 \pm 0.2836$."
        ),
        # Replacement 14
        (
            "* **Concern**: *Reviewers will notice that NO_PPI (0.8544 AUROC) outperforms FULL (0.8536 AUROC). The draft must explicitly state that the main focus of this work is explainability rather than predictive optimization.*\n* **Response**: We agree. We have added a dedicated disclaimer to Section 5.5.2 and Section 5.6 point 5: *\"Crucially, the primary contribution of this work is explainability evaluation rather than demonstrating predictive utility of PPI-enhanced message passing; we focus on benchmarking how explainers reflect internal model weights under different structural densities.\"* This prevents reviewers from questioning the inclusion of PPI.",
            "* **Concern**: *Reviewers will notice that NO_PPI (0.8543 AUROC) outperforms FULL (0.8538 AUROC). The draft must explicitly state that the main focus of this work is explainability rather than predictive optimization.*\n* **Response**: We agree. We have added a dedicated disclaimer to Section 5.5.2 and Section 5.6 point 5: *\"Crucially, the primary contribution of this work is explainability evaluation rather than demonstrating predictive utility of PPI-enhanced message passing; we focus on benchmarking how explainers reflect internal model weights under different structural densities.\"* This prevents reviewers from questioning the inclusion of PPI."
        )
    ]

    print("Starting updates in reviewer_responses.md...")
    success_count = 0
    for i, (old_t, new_t) in enumerate(replacements, 1):
        if old_t in content:
            content = content.replace(old_t, new_t)
            print(f"Replacement {i} matched and replaced.")
            success_count += 1
        else:
            # Try replacing with generalized carriage returns
            old_t_norm = old_t.replace('\r\n', '\n')
            content_norm = content.replace('\r\n', '\n')
            if old_t_norm in content_norm:
                content_norm = content_norm.replace(old_t_norm, new_t.replace('\r\n', '\n'))
                content = content_norm
                print(f"Replacement {i} matched and replaced after normalization.")
                success_count += 1
            else:
                print(f"Replacement {i} failed to match.")

    responses_path.write_text(content)
    print(f"Done. Successfully applied {success_count} / {len(replacements)} replacements.")

if __name__ == "__main__":
    main()
